### ISSUE TITLE
Binary `flang` package for Linux 

### ISSUE THREAD

**Issue by zaikunzhang** [carlocab/homebrew-personal#110]
Hello @carlocab !

As discussed on [Fortran Discourse](https://fortran-lang.discourse.group/t/using-flang-in-github-actions/2546/), it would be very nice if a binary `flang` package for Linux can be made available so that it can be easily usable in GitHub Actions (with ubuntu-latest). There is a [binary release available](https://github.com/flang-compiler/flang/releases/tag/flang_20190329), but it is a bit old, dating back to March 2019. I understand that it will take quite some work to prepare such a package, but it will be much appreciated by the Fortran community. I look forward to seeing it when you find time to do so. Thank you very much!

Best regards,
Zaikun

**Comment by carlocab** [comment]
Do you plan to use this only on GitHub Actions, or will you use it locally too?

The former is easy; the latter is what might require a little work (needed to guarantee portability).

**Comment by carlocab** [comment]
Ok, I pushed some changes that should hopefully let me build a binary package for Linux. Let's see if it works.

**Comment by carlocab** [comment]
Closed in c51927ed4cc72de0ed47091bb9bbbdfcd800bc2f. `brew install carlocab/personal/flang` should now work on GitHub Actions runners.

**Comment by zaikunzhang** [comment]
Sorry for the delayed reply. I confirm that it works with GitHub Acrtions. Excellent! Thank you very much for your efforts!
